name: Periodic health check

    
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '*/60 */24 * * *' '*/2 * * * *'
    

on:
  push:
    branches:  [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 */24 * * *'
    
  workflow_dispatch:
     
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
    - name: ping
      uses: jtalk/url-health-check-action@v1.2
      with:
          # Check the following URLs one by one sequentially
        url: https://blogsamu.herokuapp.com/
       
